FROM rust:1.84 AS builder
WORKDIR /usr/src/podman-socket-proxy
COPY . .
RUN cargo install --path .

FROM debian:bookworm-slim
RUN apt-get update && rm -rf /var/lib/apt/lists/*
WORKDIR /proxy
COPY --from=builder /usr/local/cargo/bin/podman-socket-proxy /proxy/podman-socket-proxy
COPY ./config.toml /proxy/config.toml

EXPOSE 8787

CMD ["/proxy/podman-socket-proxy", "inet"]