
#
# Regex Expression recommendations:
# - Use ^ at the start
# - Use $ at the end
# - Be carefull of potential arguments in URI's
#

[filters.get]
allowed = true
regex = '^/v1\..{1,2}/(version|containers/.*|events.*)$'

[filters.head]
allowed = false
regex = ''

[filters.post]
allowed = false
regex = ''

[filters.put]
allowed = false
regex = ''

[filters.patch]
allowed = false
regex = ''

[filters.delete]
allowed = false
regex = ''